version : '3.7'

services:

  hiveos:
    image: hiveos
    container_name: hiveos
    restart: 'unless-stopped'
    volumes:
    - ./:/hiveos/
#     networks: 
#       - network1

# networks:
#   network1:
#     name: my-pre-existing-network
#     external: true